# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180214_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=300),
        ),
    ]
